DROP TABLE IF EXISTS Items;
DROP TABLE IF EXISTS ItemBids;
DROP TABLE IF EXISTS Bids;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Category;

CREATE TABLE Items(ItemID INTEGER NOT NULL PRIMARY KEY,
				   Name CHAR(300) NOT NULL,
				   Started TIMESTAMP NOT NULL,
				   Ends TIMESTAMP NOT NULL,
				   SellerID CHAR(300) NOT NULL,
				   Description TEXT NOT NULL,
				   FOREIGN KEY (SellerID) REFERENCES Users(UserID));

CREATE TABLE ItemBids(ItemID INTEGER PRIMARY KEY,
					  Currently DECIMAL NOT NULL,
					  First_Bid DECIMAL NOT NULL,
					  Number_of_Bids INTEGER NOT NULL,
					  FOREIGN KEY (ItemID) REFERENCES Items(ItemID));

CREATE TABLE Bids(ItemID INTEGER,
				  UserID CHAR(300) NOT NULL,
				  Time TIMESTAMP NOT NULL,
				  Amount DECIMAL NOT NULL,
				  FOREIGN KEY (ItemID) REFERENCES Items(ItemID),
				  FOREIGN KEY (UserID) REFERENCES Users(UserID),
				  PRIMARY KEY (ItemID, UserID, Amount));

CREATE TABLE Users(UserID CHAR(300) PRIMARY KEY,
				   Location CHAR(300),
				   Country CHAR(300),
				   Rating INTEGER NOT NULL);

CREATE TABLE Category(ItemID INTEGER,
					  Category_Names CHAR(300),
					  FOREIGN KEY (ItemID) REFERENCES Items(ItemID),
					  PRIMARY KEY (ItemID, Category_Names));